const questions = [
    "What’s your definition of a fulfilling life?",
    "What do you think is your life’s purpose?",
    "Do we create our own destiny, or is everything predetermined?",
    "What’s a principle you try to live by every day?",
    "What’s something you’ve learned about yourself this year?",
    "If you could change one thing about the world, what would it be?",
    "What makes you feel most alive?",
    "How do you handle failure?",
    "Do you believe people can change?",
    "How do you measure success in life?",
    "What’s a moment that changed your perspective on life?",
    "What are you most grateful for?",
    "How do you find peace during stressful times?",
    "Do you believe everything happens for a reason?",
    "What does happiness mean to you?",
    "What does love mean to you?",
    "How do you express love in a relationship?",
    "What’s the most important quality you look for in a partner?",
    "How do you handle disagreements in a relationship?",
    "What’s the biggest lesson you’ve learned from past relationships?",
    "Do you believe in soulmates?",
    "What makes a relationship strong?",
    "How do you know when you’re truly in love?",
    "What’s your love language?",
    "What’s your idea of the perfect date?",
    "Do you think long-distance relationships can work?",
    "How do you balance individuality and togetherness in a relationship?",
    "What role do trust and communication play in a relationship?",
    "How do you handle jealousy?",
    "Do you believe in love at first sight?",
    "What does commitment mean to you?",
    "What role does family play in your life?",
    "How do you balance family and personal goals?",
    "What’s a value you learned from your family that you still hold on to?",
    "How do you define a true friend?",
    "What’s the best advice someone has given you?",
    "What’s your greatest accomplishment so far?",
    "What’s your biggest regret?",
    "What memory instantly makes you smile?",
    "Have you ever lost someone close to you?",
    "How have your priorities changed over time?",
    "What bad habit have you successfully stopped?",
    "What advice would you give your younger self?",
    "What’s something you think is underrated in life?",
    "Do you think money can buy happiness?",
    "Would you sacrifice yourself for a stranger?",
    "Do you think artificial intelligence will benefit or harm humanity?",
    "What’s the one thing that should be taught in school but isn’t?",
    "How important is freedom of speech?",
    "Do dreams have meanings?",
    "Which is more real—mind or matter?",
    "Do we have a greater purpose?",
    "Where do you think we go when we die?",
    "Do you believe in life after death?",
    "Is time a human construct or a natural law?"
  ]

export default questions;